default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: localhost

development:
  <<: *default
  database: agenda_development

test:
  <<: *default
  database: agenda_test
